using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace HomeApp.Commute;

// A small database document keeps private routes, profiles and maps configuration together.
// Only non-location-specific schema/model definitions belong in the tracked project.
public sealed class RouteSettingsStore(IServiceScopeFactory scopes, IConfiguration config,
    IHostEnvironment environment, ILogger<RouteSettingsStore> logger)
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);
    private readonly SemaphoreSlim _gate = new(1);
    private CommuteWorkspace _workspace = new();
    public bool Available { get; private set; }
    public CommuteWorkspace Workspace => Copy(Volatile.Read(ref _workspace));
    public CommuteRoute? Current { get { var w = Workspace; return w.Routes.FirstOrDefault(r => r.Id == w.ActiveRouteId); } }
    private static CommuteWorkspace Copy(CommuteWorkspace w) => JsonSerializer.Deserialize<CommuteWorkspace>(JsonSerializer.Serialize(w, JsonOptions), JsonOptions)!;
    public WorkspaceDto PublicWorkspace()
    {
        var w = Workspace;
        return new(w.Routes, w.Dashboards, w.ActiveRouteId, w.ActiveDashboardId, w.GoogleMapsEmbedKey.Length > 0);
    }
    public async Task InitializeAsync(CancellationToken ct)
    {
        if (Available) return;
        await _gate.WaitAsync(ct);
        try
        {
            if (Available) return;
            using var scope = scopes.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<CommuteDbContext>();
            // Empty schema bootstrap only. No user-specific data is generated by tracked code.
            var schema = db.Database.GenerateCreateScript().Replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", StringComparison.Ordinal);
            await db.Database.ExecuteSqlRawAsync(schema, ct);
            await ApplyPrivateMigrationsAsync(db, ct);
            var row = await db.Workspaces.SingleOrDefaultAsync(x => x.Id == 1, ct);
            if (row is null)
            {
                row = new WorkspaceRow { Json = JsonSerializer.Serialize(new CommuteWorkspace(), JsonOptions), Revision = 1 };
                db.Workspaces.Add(row); await db.SaveChangesAsync(ct);
            }
            var workspace = JsonSerializer.Deserialize<CommuteWorkspace>(row.Json, JsonOptions) ?? throw new JsonException();
            foreach (var route in workspace.Routes) if (Validate(route) is { } error) throw new InvalidOperationException(error);
            Volatile.Write(ref _workspace, workspace); Available = true;
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested) { throw; }
        catch (Exception) { logger.LogWarning("Commute database settings unavailable. Connection, schema and private migrations should be checked. Will retry."); }
        finally { _gate.Release(); }
    }
    private async Task ApplyPrivateMigrationsAsync(CommuteDbContext db, CancellationToken ct)
    {
        var directory = config["Commute:PrivateMigrationsPath"];
        if (string.IsNullOrWhiteSpace(directory))
        {
            for (var p = new DirectoryInfo(environment.ContentRootPath); p is not null; p = p.Parent)
            {
                var candidate = Path.Combine(p.FullName, ".devcontainer", "private-migrations", "commute");
                if (Directory.Exists(candidate)) { directory = candidate; break; }
                // Keep existing installations with root-level private migrations working.
                candidate = Path.Combine(p.FullName, "private-migrations", "commute");
                if (Directory.Exists(candidate)) { directory = candidate; break; }
            }
        }
        if (string.IsNullOrWhiteSpace(directory) || !Directory.Exists(directory)) return;
        foreach (var file in Directory.GetFiles(directory, "*.sql").Order(StringComparer.Ordinal))
        {
            var sql = await File.ReadAllTextAsync(file, ct); var id = Path.GetFileName(file);
            var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(sql)));
            var existing = await db.PrivateMigrations.FindAsync([id], ct);
            if (existing is not null)
            {
                if (existing.Hash != hash) throw new InvalidOperationException("An applied private migration was changed. Add a new migration instead.");
                continue;
            }
            await using var tx = await db.Database.BeginTransactionAsync(ct);
            await db.Database.OpenConnectionAsync(ct);
            await using var command = db.Database.GetDbConnection().CreateCommand();
            command.CommandText = sql; command.Transaction = tx.GetDbTransaction();
            await command.ExecuteNonQueryAsync(ct);
            db.PrivateMigrations.Add(new() { Id = id, Hash = hash }); await db.SaveChangesAsync(ct);
            await tx.CommitAsync(ct);
        }
    }
    public static string? Validate(CommuteRoute r)
    {
        if (string.IsNullOrWhiteSpace(r.Name) || r.Name.Length > 120 || string.IsNullOrWhiteSpace(r.Origin)
            || string.IsNullOrWhiteSpace(r.Destination) || r.Origin.Length > 120 || r.Destination.Length > 120)
            return "Route name, origin and destination are required (up to 120 characters each).";
        if (r.Points is null || r.Points.Length is < 2 or > 100 || r.Points.Any(p => p is null || !RouteGeometry.Valid(p))
            || r.Points.Zip(r.Points.Skip(1)).Sum(pair => RouteGeometry.Distance(pair.First, pair.Second)) < .1)
            return "Provide 2–100 valid latitude/longitude points in travel order, covering at least 100 metres.";
        if (!double.IsFinite(r.CorridorKm) || r.CorridorKm is < .1 or > 10) return "Corridor width must be 0.1–10 km.";
        if (r.Roadways is null || r.Roadways.Length is < 1 or > 20 || r.Roadways.Any(s => string.IsNullOrWhiteSpace(s) || s.Length > 80))
            return "Provide 1–20 roadway names or aliases (up to 80 characters each).";
        if (r.AlertRegions is null || r.AlertRegions.Length > 5 || r.AlertRegions.Any(s => string.IsNullOrWhiteSpace(s) || s.Length > 80))
            return "Provide up to five provider region names (up to 80 characters each).";
        if (r.Direction is not ("All Directions" or "Eastbound" or "Westbound" or "Northbound" or "Southbound" or "Inbound" or "Outbound"))
            return "Select a valid travel direction.";
        if (r.MarineBounds is { } b && (!RouteGeometry.Valid(new(b.MinLatitude, b.MinLongitude)) || !RouteGeometry.Valid(new(b.MaxLatitude, b.MaxLongitude))
            || b.MinLatitude >= b.MaxLatitude || b.MinLongitude >= b.MaxLongitude
            || (b.MaxLatitude - b.MinLatitude) * (b.MaxLongitude - b.MinLongitude) > 100))
            return "Marine bounds must be ordered valid coordinates, with an area no greater than 100 square degrees.";
        if (r.Bridge is { } bridge && (string.IsNullOrWhiteSpace(bridge.Name) || bridge.Name.Length > 120
            || bridge.Position is null || !RouteGeometry.Valid(bridge.Position) || !double.IsFinite(bridge.InboundBearing) || bridge.InboundBearing is < 0 or >= 360))
            return "Provide a bridge name, valid position and inbound canal bearing (0–359 degrees).";
        return null;
    }
    public async Task<CommuteRoute> SaveAsync(CommuteRoute route, CancellationToken ct)
    {
        if (Validate(route) is { } error) throw new ArgumentException(error);
        var saved = route with { Id = route.Id == Guid.Empty ? Guid.NewGuid() : route.Id };
        await ChangeAsync(w => w with {
            Routes = w.Routes.Where(r => r.Id != saved.Id).Append(saved).ToArray(), ActiveRouteId = saved.Id,
            Dashboards = w.Dashboards.Select(p => p.Id == w.ActiveDashboardId && !p.RouteIds.Contains(saved.Id)
                ? p with { RouteIds = p.RouteIds.Append(saved.Id).ToArray() } : p).ToArray()
        }, ct);
        return saved;
    }
    public async Task ChangeAsync(Func<CommuteWorkspace, CommuteWorkspace> change, CancellationToken ct)
    {
        await InitializeAsync(ct);
        if (!Available) throw new InvalidOperationException("Database settings unavailable.");
        await _gate.WaitAsync(ct);
        try
        {
            using var scope = scopes.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<CommuteDbContext>();
            var row = await db.Workspaces.SingleAsync(x => x.Id == 1, ct);
            var updated = Copy(change(JsonSerializer.Deserialize<CommuteWorkspace>(row.Json, JsonOptions)!));
            row.Json = JsonSerializer.Serialize(updated, JsonOptions); row.Revision++;
            await db.SaveChangesAsync(ct); Volatile.Write(ref _workspace, updated);
        }
        finally { _gate.Release(); }
    }
}
