// <auto-generated />
using System;
using HomeApp.Expenses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeApp.Expenses.Migrations
{
    [DbContext(typeof(HomeAppExpensesDbContext))]
    [Migration("20260823200004_addExpenseItemCanonicalNames")]
    partial class addExpenseItemCanonicalNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseAgentSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultCurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractionPrompt")
                        .HasColumnType("text");

                    b.Property<string>("ModelKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ExpenseAgentSettings");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnalysisConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DuplicateFingerprint")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExpenseGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ImportFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImportSchemaKey")
                        .HasColumnType("text");

                    b.Property<string>("ImportSourceReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsReimbursable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkExpense")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text");

                    b.Property<string>("ModelKeyUsed")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("RawExtractionJson")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptFileName")
                        .HasColumnType("text");

                    b.Property<byte[]>("ReceiptImageBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ReceiptImageContentType")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptText")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TipAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DuplicateFingerprint");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("ExpenseDate", "ExpenseGroupId");

                    b.ToTable("ExpenseEntries");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "DisplayOrder");

                    b.ToTable("ExpenseGroups");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ExpenseEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("ExpenseEntryId", "NormalizedName");

                    b.ToTable("ExpenseLineItems");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseEntry", b =>
                {
                    b.HasOne("HomeApp.Expenses.Data.ExpenseGroup", "ExpenseGroup")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExpenseGroup");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseLineItem", b =>
                {
                    b.HasOne("HomeApp.Expenses.Data.ExpenseEntry", "ExpenseEntry")
                        .WithMany("LineItems")
                        .HasForeignKey("ExpenseEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseEntry");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseEntry", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HomeApp.Expenses.Data.ExpenseGroup", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
