#!/usr/bin/env bash
set -euo pipefail

# VS Code runs this on the host before Docker Compose reads its configuration.
# These development credentials stay local and are never checked into Git.
devcontainer_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
devcontainer_env="${devcontainer_dir}/.env"
umask 077
if [[ -L "${devcontainer_env}" ]]; then
    echo "Refusing to write development credentials through a symlink." >&2
    exit 1
fi
if [[ ! -f "${devcontainer_env}" ]]; then
    printf '# Local development credentials generated by initialize-env.sh\n' > "${devcontainer_env}"
fi
for credential_name in POSTGRES_PASSWORD PGADMIN_DEFAULT_PASSWORD GRAFANA_ADMIN_PASSWORD; do
    if ! grep -qE "^${credential_name}=.+$" "${devcontainer_env}"; then
        credential_value="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
        printf '\n%s=%s\n' "${credential_name}" "${credential_value}" >> "${devcontainer_env}"
    fi
done
chmod 600 "${devcontainer_env}"
