<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>



  <ItemGroup>
    <ProjectReference Include="..\HomeApp.Commute\HomeApp.Commute.csproj" />
    <ProjectReference Include="..\HomeApp.SecuritySystem\HomeApp.SecuritySystem.csproj" />
    <ProjectReference Include="..\HomeApp.Videos\HomeApp.Videos.csproj" />
    <ProjectReference Include="..\HomeApp.Expenses\HomeApp.Expenses.csproj" />
    <ProjectReference Include="..\HomeApp.AI\HomeApp.AI.csproj" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.2" />
  </ItemGroup>

</Project>
